### ISSUE TITLE
feat: 챌린지 시작 trigger

### ISSUE THREAD

**Issue by chaeyeon-yang** [Do-Farming/Do-Farming_Back#11]
## 📌 Issue

방장이 설정한 챌린지 인원이 다 찼을 때 
챌린지 상태를 진행중으로 바꾸고 해당 날짜의 차주에 챌린지가 시작되도록 스케쥴링

## 📜 To-do

- [ ] 챌린지 인원이 설정한 인원과 같은지 확인
- [ ] 챌린지 상태 변경
- [ ] 차주에 챌린지 시작되도록 스케쥴링
